### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by xolatgames**
Hello, bodies! So, I do everything right for this time?

### CODE REVIEW

**Comment by hfiguiere** [comment]
Non versioned URL are a bad idea. The content should never change on the other side. If it's a new version it should be a new URL. (putting the version in the file name is an easy way to do that).

**Comment by hfiguiere** [comment]
in a case of github, a new release works too.

**Comment by xolatgames** [comment]
Wait for a minute! I get!

**Comment by xolatgames** [comment]
Ok, guys! I do it tomorrow.

**Comment by xolatgames** [comment]
God Damned! I can't understand it!

**Comment by xolatgames** [comment]
> Non versioned URL are a bad idea. The content should never change on the other side. If it's a new version it should be a new URL. (putting the version in the file name is an easy way to do that).

Which the filename? I'm already created new release. Changed the folder name in the downloadable archive, and also renamed all files into. But I don't understand, where I should to put the version in? 😭

**Comment by xolatgames** [comment]
Help me, guys, when you will be free, pls! 😭😭😭 Just give me some hint!

**Comment by xolatgames** [comment]
It's the problem in the yml file, right?

**Comment by xolatgames** [comment]
Or in the metainfo file?

**Comment by xolatgames** [comment]
bot, build it

**Comment by xolatgames** [comment]
Yeah! Yeah! Yeah! I did it! Thanks to your forum community, bros! 😇 The test is done successfully. I had check it already! So! Let's publish this now, guys! 😊

**Comment by xolatgames** [comment]
bot, publish

**Comment by xolatgames** [comment]
bot, merge

**Comment by hfiguiere** [comment]
There is a button to click to merge.

**Comment by xolatgames** [comment]
> There is a button to click to merge.

Where?

https://github.com/flathub/io.github.xolatgames.marknpaul/assets/64919860/0bd99c52-87e4-4edc-b447-a1b5475c8b59

**Comment by xolatgames** [comment]
I remember that I accepted the invitation to make changes this repository. But probably something went wrong... 😔

**Comment by hfiguiere** [comment]
Can't view the video.

**Comment by hfiguiere** [comment]
sent a new invite. make sure you accept it this time. it will expire in a few days.

**Comment by xolatgames** [comment]
> sent a new invite. make sure you accept it this time. it will expire in a few days.

Thank so much, hfi! Have a nice day! 😉👋🏻

**Pull request merged**
